toolbox/crm/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include

app_name = 'crm'


urlpatterns = [
    path('', views.cdr_detail_view, name='cdr_detail_view'),
    path('reset/', views.reset, name="reset"),
    path('customer/', views.customer, name="customer"),
    # path('smsc/', views.smsc, name="smsc"),
    path('smsc/', views.form_submit, name='form_submit'),
]

toolbox/crm/templates/crm/base.html
{% load static %}

<html>
<head>
  <title>CRM</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  

  <link href="{% static 'crm/css/main.css' %}" rel="stylesheet">
</head>

<body>
  
    {% include 'crm/navbar.html' %}

    {% block content %}



    {% endblock %}

  <hr>
  <h5> Footer </h5>
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


</html>

toolbox/crm/templates/crm/customer.html
{% extends 'crm/base.html' %}



{% block content %}



  <br>

  <div class="row">
      <div class="col-md">
          <div class="card card-body">
              <h5>Customer:</h5>
              <hr>
              <a class="btn btn-outline-info  btn-sm btn-block" href="">Update Customer</a>
              <a class="btn btn-outline-danger  btn-sm btn-block" href="">Delete Customer</a>
  
          </div>
      </div>
  
      <div class="col-md">
          <div class="card card-body">
              <h5>Contact Information</h5>
              <hr>
              <p>Email: </p>
              <p>Phone: </p>
          </div>
      </div>
  
      <div class="col-md">
          <div class="card card-body">
              <h5>Total Orders</h5>
              <hr>
              <h1 style="text-align: center;padding: 10px"></h1>
          </div>
      </div>
  </div>
  
  
  <br>
  <div class="row">
      <div class="col">
          <div class="card card-body">
              <form method="get">
  
              <button class="btn btn-primary" type="submit">Search</button>
            </form>
          </div>
      </div>
      
  </div>
  <br>
  
  <div class="row">
      <div class="col-md">
          <div class="card card-body">
              <table class="table table-sm">
                  <tr>
                      <th>Product</th>
                      <th>Category</th>
                      <th>Date Orderd</th>
                      <th>Status</th>
                      <th>Update</th>
                      <th>Remove</th>
                  </tr>
  
              </table>
          </div>
      </div>
  </div>


{% endblock  %}

toolbox/crm/templates/crm/jquery.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.js"></script> 


    
    <script type="text/javascript">
    $(function() {
    
        $(document).ready(function () {
  
            var success_min0_smsc_2_eu4 = $('#success_min0_smsc_2_eu4')[0].innerText
            var total_min0_smsc_2_eu4 = $('#total_min0_smsc_2_eu4')[0].innerText

            var success_min1_smsc_2_eu4 = $('#success_min1_smsc_2_eu4')[0].innerText
            var total_min1_smsc_2_eu4 = $('#total_min1_smsc_2_eu4')[0].innerText

            var success_min2_smsc_2_eu4 = $('#success_min2_smsc_2_eu4')[0].innerText
            var total_min2_smsc_2_eu4 = $('#total_min2_smsc_2_eu4')[0].innerText

            var success_min3_smsc_2_eu4 = $('#success_min3_smsc_2_eu4')[0].innerText
            var total_min3_smsc_2_eu4 = $('#total_min3_smsc_2_eu4')[0].innerText

            var success_min4_smsc_2_eu4 = $('#success_min4_smsc_2_eu4')[0].innerText
            var total_min4_smsc_2_eu4 = $('#total_min4_smsc_2_eu4')[0].innerText

            var success_min5_smsc_2_eu4 = $('#success_min5_smsc_2_eu4')[0].innerText
            var total_min5_smsc_2_eu4 = $('#total_min5_smsc_2_eu4')[0].innerText

            var successPer_min0_smsc_2_eu4    = (success_min0_smsc_2_eu4 / total_min0_smsc_2_eu4) * 100;
            var successPer_min1_smsc_2_eu4    = (success_min1_smsc_2_eu4 / total_min1_smsc_2_eu4) * 100;
            var successPer_min2_smsc_2_eu4    = (success_min2_smsc_2_eu4 / total_min2_smsc_2_eu4) * 100;
            var successPer_min3_smsc_2_eu4    = (success_min3_smsc_2_eu4 / total_min3_smsc_2_eu4) * 100;
            var successPer_min4_smsc_2_eu4    = (success_min4_smsc_2_eu4 / total_min4_smsc_2_eu4) * 100;
            var successPer_min5_smsc_2_eu4    = (success_min5_smsc_2_eu4 / total_min5_smsc_2_eu4) * 100;

            $('#successPer_min0_smsc_2_eu4').html(successPer_min0_smsc_2_eu4.toFixed(2));
            $('#successPer_min1_smsc_2_eu4').html(successPer_min1_smsc_2_eu4.toFixed(2));
            $('#successPer_min2_smsc_2_eu4').html(successPer_min2_smsc_2_eu4.toFixed(2));
            $('#successPer_min3_smsc_2_eu4').html(successPer_min3_smsc_2_eu4.toFixed(2));
            $('#successPer_min4_smsc_2_eu4').html(successPer_min4_smsc_2_eu4.toFixed(2));
            $('#successPer_min5_smsc_2_eu4').html(successPer_min5_smsc_2_eu4.toFixed(2));
        });
    
    });
    </script>

toolbox/crm/templates/crm/navbar.html
{% load static %}



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <img src="{% static 'crm/img/cake2.jpg' %}" class="rounded" alt="flower">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/crm">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:reset' %}">Reset DB</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:customer' %}">Customer</a>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'crm:form_submit' %}">SMSC</a>
        </li>
      </ul>
    </div>
  </nav>

toolbox/crm/templates/crm/reset.html
{% extends 'crm/base.html' %}



{% block content %}


{% include 'crm/status.html' %}
  
  {{success_min0_smsc_2_eu4}}
  <hr>
  <br>
  <br>
  
  <hr>
  <br>

  
  <form class="" action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-large btn-primary" type="Submit" name="reset" value="Reset"/>
        </form>

<br>

{% endblock  %}

toolbox/crm/templates/crm/smsc.html
{% extends 'crm/base.html' %}


{% block content %}


{% include 'crm/status.html' %}


<hr>
<br>
<br>

<hr>
<br>
<br>



<br>
<form method='POST'> {% csrf_token %}
		{{ form.as_p }} 
	  <label for="cars">Choose a date:</label>
	  <select name="date" id="cars">
	    <option value="0">Current</option>
	    <option value="-1">One hour Ago</option>
			<option value="-2">Two hours ago</option>
			<option value="examplefile">examplefile</option>
	  </select><br><br>
	<input type="text" name="NetworkID" placeholder="NetworkID" /><br><br>
  

	<label for="smsc">Choose a system:</label>
	<select name="smsc" id="smsc">
	<option value="smsc-1-eu1-prod">smsc-1-eu1-prod</option>
	<option value="smsc-2-eu4-prod">smsc-2-eu1-prod</option>
	<option value="smsc-1-eu4-prod">smsc-1-eu4-prod</option>
	<option value="smsc-2-eu4-prod">smsc-2-eu4-prod</option>
	</select><br><br>

  <input type="submit" value="Run" />
  
</form>





{% endblock %}

toolbox/crm/templates/crm/status.html
{% load static %}
<link href="{% static 'crm/css/main.css' %}" rel="stylesheet">

<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Time of extraction from SMSC to DB</h5>
			  	</div>
			  	<div class="card-body">
					<h3 class="card-title"></h3>
					<th>
						<td>
							<h2>   {{final_time}}   </h2>	
						</td>
					</th>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Total cdr records</h5>
			  	</div>
			  	<div class="card-body">
					<h3 class="card-title"></h3>
					<th>
							<td>
								<h2>   {{ count_total_smsc_2_eu4 }}   </h2>	
							</td>
						</th>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">TBD</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
			  	</div>
			</div>
		</div>
	</div>
</div>