crm/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include

app_name = 'crm'


urlpatterns = [
    path('', views.cdr_detail_view, name='cdr_detail_view'),
    # path('reset/', views.reset, name="reset"),
    path('customer/', views.customer, name="customer"),
    path('smsc/', views.form_submit, name='form_submit'),
    path('esme_dlr/', views.esme_dlr, name='esme_dlr'),
    path('esme_dlr_view/', views.esme_dlr_view, name='esme_dlr_view'),
    path('sendSMS/', views.sendSMS, name='sendSMS'),
    path('sendSMS/<str:room_name>/', views.sendSMSroom, name='sendSMSroom'),
    path('chat_box/', views.chat_box, name='chat_box'),
    path('chat_box/<str:room_name>/', views.chatboxroom, name='chatboxroom'),
    path('fb/', views.fb, name='fb'),
    path('ss7hub/', views.ss7hub, name='ss7hub'),
    path('srilookup/', views.srilookup, name='srilookup'),
    # path('newSG/', views.newSG, name='newSG'),
    path('newSGv3/', views.newSGv3, name='newSGv3'),
]

crm/templates/crm/base.html
{% load static %}

<html>
<head>
  <title>CRM</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  

  <link href="{% static 'crm/css/main.css' %}" rel="stylesheet">
</head>

<body>
  
    {% include 'crm/navbar.html' %}

    {% block content %}



    {% endblock %}

  <hr>
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


</html>

crm/templates/crm/chat_box.html
{% extends 'crm/base.html' %}

{% block content %}
<br>


  <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>ChatBox</title>
  </head>
  <body>
    <br>
    <h1>ChatBox</h1>


  
    <input type="text" placeholder="Enter chatgroup..." id="txtName"/>
    <a href = "javascript:;" onclick = "this.href='' + document.getElementById('txtName').value">Connect</a>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock  %}

crm/templates/crm/esme_dlr.html
{% extends 'crm/base.html' %}
{% block content %}

{% include 'crm/statusdlr.html' %}


<br>
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <label for="dlr">Choose a date:</label>
    <select name="date" id="dlr">
        <option value="0">Current</option>
        <option value="-1">One hour Ago</option>
        <option value="examplefile">examplefile</option>
    </select><br><br>

    <label for="smsc">Choose a system:</label>
    <select name="smsc" id="smsc">
        <option value="smsc-1-eu1-prod">smsc-1-eu1-prod</option>
        <option value="smsc-2-eu4-prod">smsc-2-eu1-prod</option>
        <option value="smsc-1-eu4-prod">smsc-1-eu4-prod</option>
        <option value="smsc-2-eu4-prod">smsc-2-eu4-prod</option>
    </select><br><br>
    <input type="submit" value="Run" />
</form>

<hr>
<br>
<br>

<form class="" action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-large btn-primary" type="Submit" name="reset" value="Reset" />
</form>



<div class="row">
    <div class="col-md-6">
        <!-- <a >Total missing DLRs SG</a> -->
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary  btn-sm btn-block" id="total_sg_count" href="">Total missing DLRs SG</a>
            <table class="table table-sm">
                <tr>
                    <th>Time</th>
                    <th>MsIsdn</th>
                    <th>MessageId</th>
                    <th>SenderId</th>
                    <th>System</th>
                </tr>
                {% for i in total_sg %}
                <tr>
                <tr>
                    <td>{{ i.time}}</td>
                    <td>{{ i.msisdn }}</td>
                    <td>{{ i.messageid }}</td>
                    <td>{{ i.senderid }}</td>
                    <td>{{ i.system }}</td>
                </tr>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-6">
        <!-- <a >Total missing DLRs DBS Bank</a> -->
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary  btn-sm btn-block" id="total_dbs_count" href="">Total missing DLRs DBS Bank</a>
            <table class="table table-sm">
                <tr>
                    <th>Time</th>
                    <th>MsIsdn</th>
                    <th>MessageId</th>
                    <th>SenderId</th>
                    <th>System</th>
                </tr>
                {% for i in total_dbs %}
                <tr>
                <tr>
                    <td>{{ i.time}}</td>
                    <td>{{ i.msisdn }}</td>
                    <td>{{ i.messageid }}</td>
                    <td>{{ i.senderid }}</td>
                    <td>{{ i.system }}</td>
                </tr>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

<br><br><br>

<form method="get" action="../esme_dlr_view/">
    <button type="submit">pictures</button>
</form>

<br>
{% endblock  %}

crm/templates/crm/esme_dlr_reset.html
{% extends 'crm/base.html' %}
{% load static %}

{% block content %}


  <hr>
  <br>
  <br>
  <hr>


<br>
<br>
<br>
<br>
<br>

  <img src="{% static 'crm/img/admin.png' %}" class="rounded" alt="flower">
<br>
<hr>
<br>
<br>
<br>

  <img src="{% static 'crm/img/admin1.png' %}" class="rounded" alt="flower"> -->
  <br>
  <br>
  <br>

<br>
<hr>
<br>
<br>
<br>

  <img src="{% static 'crm/img/cassandra.png' %}" class="rounded" alt="flower"> -->
  <br>
  <br>
  <br>

<br>
<hr>
<br>

  <img src="{% static 'crm/img/buffered.png' %}" class="rounded" alt="flower"> -->
  <br>
  <br>
  <br>


  <br>
  <hr>
<br>


  <img src="{% static 'crm/img/expired.png' %}" class="rounded" alt="flower"> -->
  <br>
  <br>
  <br>
<br>


  {% endblock  %}

crm/templates/crm/navbar.html
{% load static %}



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <img src="{% static 'crm/img/cake2.jpg' %}" class="rounded" alt="flower">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:newSGv3' %}">SG</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:fb' %}">FB</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:form_submit' %}">SMSC</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:esme_dlr' %}">ESME_DLR</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:sendSMS' %}">sendSMS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:chat_box' %}">Chat_Box</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:ss7hub' %}">ss7hub</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crm:srilookup' %}">srilookup</a>
        </li>
      </ul>
    </div>
  </nav>

crm/templates/crm/reset.html
{% extends 'crm/base.html' %}



{% block content %}


{% include 'crm/status.html' %}
  
  {{success_min0_smsc_2_eu4}}
  <hr>
  <br>
  <br>
  
  <hr>
  <br>

  
  <form class="" action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-large btn-primary" type="Submit" name="reset" value="Reset" />
  </form>

<br>

{% endblock  %}

crm/templates/crm/sendSMS.html
{% extends 'crm/base.html' %}

{% block content %}

<br>


  <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>Hello, world!</title>
  </head>
  <body>
    <br>
    <h1>Python smpplib SendBox</h1>


  
    <input type="text" placeholder="Add MsIsdn" id="txtName"/>
    <a href = "javascript:;" onclick = "this.href='' + document.getElementById('txtName').value">Next</a>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock  %}

crm/templates/crm/srilookup.html
{% extends 'crm/base.html' %}

{% block content %}

<h1>Coming next</h1>


{% endblock  %}

crm/templates/crm/status.html
{% load static %}
<link href="{% static 'crm/css/main.css' %}" rel="stylesheet">

<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Time of extraction from SMSC to DB</h5>
			  	</div>
			  	<div class="card-body">
					<h3 class="card-title"></h3>
					<th>
						<td>
							<h2>   {{final_time}}   </h2>	
						</td>
					</th>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Total cdr records</h5>
			  	</div>
			  	<div class="card-body">
					<h3 class="card-title"></h3>
					<th>
							<td>
								<h2>   {{ count_total_smsc_2_eu4 }}   </h2>	
							</td>
						</th>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">TBD</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
			  	</div>
			</div>
		</div>
	</div>
</div>

crm/templates/crm/statusdlr.html
{% load static %}
<link href="{% static 'crm/css/main.css' %}" rel="stylesheet">

<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total_dlr_count">
			  	<div class="card-header">
			  		<h5 class="card-title">Total missing DLRs</h5>
			  	</div>
			  	<div class="card-body">
					<h3 class="card-title"></h3>
					<th>
						<td>
							<h2>   {{ total_dlr_count }}   </h2>	
						</td>
					</th>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total_sg_count">
			  	<div class="card-header">
			  		<h5 class="card-title">Total missing DLRs SG</h5>
			  	</div>
			  	<div class="card-body">
					<h3 class="card-title"></h3>
					<th>
							<td>
								<h2>   {{ total_sg_count }}   </h2>	
							</td>
						</th>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total_dbs_count">
			  	<div class="card-header">
			  		<h5 class="card-title">Total missing DLRs DBS Bank</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
                    <th>
                        <td>
                            <h2>   {{ total_dbs_count }}   </h2>	
                        </td>
                    </th>
			  	</div>
			</div>
		</div>
	</div>
</div>